language: python
python: 3.4
env:
  - TOX_ENV=py34
  - TOX_ENV=flake8
script:
    - tox -e $TOX_ENV
install:
    - pip install tox
notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
after_success:
  - .coveralls.sh
